### ISSUE TITLE
Understanding the plugin and feature request

### ISSUE THREAD

**Issue by despecial** [xorith/HideComments#4]
Hi there,

on our old forum we had an option to hide irrelevant comments and this was global for everyone.

We installed your plugin and it works nice, even though it lacks of locales support (e.g. german)

I tested it and as admin/moderator, I hid some comments but strangely, as a moderator, I still see them. So are they hidden for the user only? (this would be a let down)

In another thread, yout mentioned this:

> I'm working on an update that will provide both a settings screen under the dashboard and a toggle to allow discussion authors to hide comments in their discussion - similarly to how it is done now per user, but this would be applied to the entire discussion, allowing authors to moderate their content.

Will you work on this or did you abandon the great plugin?

Thanks for the feedback!

**Comment by keenan-v1** [comment]
Hello!

It's been about five years since I last touched this plugin, so sadly I suppose that falls under abandonment. I no longer use Vanilla Forums and currently have plenty of other projects to keep me busy - both work and play.

I don't see any reason it wouldn't hide for an admin or moderator code-wise, but then it has been five years and there could be incompatibilities by now.

Sorry that this is rather not helpful. Thank you for your comment!

**Comment by despecial** [comment]
Thanks for your feedback - appreciated. 

I crossposted this on the vanilla forums, too, and someone was inspired and said he would try to update the extension.
